import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"store 测试","description":"","frontmatter":{},"headers":[],"relativePath":"cookbook/testing.md","filePath":"cookbook/testing.md"}');
const _sfc_main = { name: "cookbook/testing.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="testing-stores" tabindex="-1">store 测试 <a class="header-anchor" href="#testing-stores" aria-label="Permalink to &quot;store 测试 %{#testing-stores}%&quot;">​</a></h1><p>从设计上来说，许多地方都会使用 store，所以可能比正常情况更难测试。但幸运的是，这不一定是真的。在测试 store 时，我们需要注意三件事：</p><ul><li><code>pinia</code> 实例：没有它，store 不能正常工作</li><li><code>actions</code>：大多数时候，它们包含了 store 最复杂的逻辑。如果它们默认就可以被 mocked，那不是很好吗？</li><li>插件：如果你依赖插件，你也必须为测试安装它们</li></ul><p>根据测试的内容和方式，我们需要以不同的方式来处理这三个问题：</p><ul><li><a href="#testing-stores">store 测试</a><ul><li><a href="#unit-testing-a-store">对 store 单元测试</a></li><li><a href="#unit-testing-components">对组件单元测试</a><ul><li><a href="#initial-state">初始 state</a></li><li><a href="#customizing-behavior-of-actions">自定义 action 的行为</a></li><li><a href="#specifying-the-creespy-function">指定 createSpy 函数</a></li><li><a href="#mocking-getters">Mocking getters</a></li><li><a href="#pinia-plugins">Pinia 插件</a></li></ul></li><li><a href="#e2e-tests">端到端测试</a></li><li><a href="#unit-test-components-vue-2">对组件单元测试(Vue 2)</a></li></ul></li></ul><h2 id="unit-testing-a-store" tabindex="-1">对 store 进行单元测试 <a class="header-anchor" href="#unit-testing-a-store" aria-label="Permalink to &quot;对 store 进行单元测试 %{#unit-testing-a-store}%&quot;">​</a></h2><p>要对一个 store 进行单元测试，最重要的是创建一个 <code>pinia</code> 实例：</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// stores/counter.spec.ts</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../src/stores/counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">describe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Counter Store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  beforeEach</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // 创建一个新 pinia，并使其处于激活状态，这样它就会被任何 useStore() 调用自动接收</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // 而不需要手动传递：</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // \`useStore(pinia)\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">())</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  it</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">increments</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">0</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  it</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">increments by amount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">10</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">10</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><p>如果你有使用任何 store 的插件，有一件重要的事情需要了解：<strong>在 <code>pinia</code> 被安装在一个应用之后，插件才会被使用</strong>。可以通过创建一个空的或假的应用来解决这个问题：</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createApp</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">vue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../src/stores/plugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 和前面一样的代码...</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 测试前你不需要创建应用</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> app</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createApp</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({})</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">beforeEach</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">().</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">use</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">  app</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">use</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><h2 id="unit-testing-components" tabindex="-1">对组件单元测试 <a class="header-anchor" href="#unit-testing-components" aria-label="Permalink to &quot;对组件单元测试 %{#unit-testing-components}%&quot;">​</a></h2><p>这可以通过 <code>createTestingPinia()</code> 实现，它会返回一个仅用于帮助对组件单元测试的 pinia 实例。</p><p>从安装 <code>@pinia/testing</code> 开始：</p><div class="language-shell vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">shell</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}"> i</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B" })}"> -D</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}"> @pinia/testing</span></span></code></pre></div><p>确保挂载组件时，在你的测试中创建一个用于测试的 pinia 实例：</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@vue/test-utils</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 引入任何你想要测试的 store</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@/stores/myStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // // 使用 pinia 的测试实例!</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 可直接操作 state</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">my new name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 也可以通过 patch 来完成</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">$patch</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}"> name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">new name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">new name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// action 默认是存根的(stubbed)，意味着它们默认不执行其代码。</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 请看下面的内容来定制这一行为。</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toHaveBeenCalledTimes</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toHaveBeenLastCalledWith</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span></code></pre></div><p>请注意，如果你使用的是 Vue 2，<code>@vue/test-utils</code> 需要一个<a href="#unit-test-components-vue-2">轻微不同的配置</a>。</p><h3 id="initial-state" tabindex="-1">初始 State <a class="header-anchor" href="#initial-state" aria-label="Permalink to &quot;初始 State %{#initial-state}%&quot;">​</a></h3><p>在创建测试 Pinia 时，你可以通过传递一个 <code>initialState</code> 对象来设置<strong>所有 store 的初始状态</strong>。这个对象将被 pinia 的测试实例用于创建 store 时 <em>patch</em> store。比方说，你想初始化这个 store 的状态：</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> () </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({ </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 0</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">  // ...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><p>由于 store 的名字是 <em>&quot;counter&quot;</em>，所以你需要传递相应的对象给 <code>initialState</code>：</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 在测试中的某处</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">      createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">        initialState</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">          counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> { </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 20</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }, </span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">//从 20 开始计数，而不是 0</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">        },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 使用 pinia 的测试实例!</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 20</span></span></code></pre></div><h3 id="customizing-behavior-of-actions" tabindex="-1">自定义 action 的行为 <a class="header-anchor" href="#customizing-behavior-of-actions" aria-label="Permalink to &quot;自定义 action 的行为 %{#customizing-behavior-of-actions}%&quot;">​</a></h3><p>除非另有指示，<code>createTestingPinia</code> 会存根 (stub) 出所有的 store action。这样可以让你独立测试你的组件和 store。</p><p>如果你想恢复这种行为，并在测试中正常执行 action，请在调用 <code>createTestingPinia</code> 时指定 <code>stubActions: false</code>：</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}"> stubActions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#1E754F" })}"> false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> })],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 现在，这个调用将由 store 定义的实现执行。</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// ...但它仍然被一个 spy 包装着，所以你可以检查调用</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toHaveBeenCalledTimes</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span></code></pre></div><h3 id="specifying-the-createspy-function" tabindex="-1">指定 createSpy 函数 <a class="header-anchor" href="#specifying-the-createspy-function" aria-label="Permalink to &quot;指定 createSpy 函数 %{#specifying-the-createspy-function}%&quot;">​</a></h3><p>当使用 Jest，或 vitest 且设置 <code>globals: true</code> 时，<code>createTestingPinia</code> 会自动使用现有测试框架 (<code>jest.fn</code> 或 <code>vitest.fn</code>) 的 spy 函数存根 (stub) action。如果你使用的是不同的框架，你需要提供一个 <a href="/en/api/interfaces/pinia_testing.TestingOptions.html#createspy">createSpy</a> 选项：</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> sinon</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">sinon</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  createSpy</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> sinon</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">spy</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 使用 sinon&#39;s spy 包装 action</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><p>你可以在<a href="https://github.com/vuejs/pinia/blob/v2/packages/testing/src/testing.spec.ts" target="_blank" rel="noreferrer">测试包的测试源码</a>中找到更多的例子。</p><h3 id="mocking-getters" tabindex="-1">Mocking getters <a class="header-anchor" href="#mocking-getters" aria-label="Permalink to &quot;Mocking getters %{#mocking-getters}%&quot;">​</a></h3><p>默认情况下，任何 getter 都会像常规用法一样进行计算，但你可以通过将 getter 设置为任何你想要的值来手动强制计算：</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> () </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({ </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  getters</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> (</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">) </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> *</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 2</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 3</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 🪄 getter 仅在测试中可被重写</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 设置为 undefined，以重置默认行为</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// @ts-expect-error: usually it&#39;s a number</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#AB5959" })}"> undefined</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 2 (=1 x 2)</span></span></code></pre></div><h3 id="pinia-plugins" tabindex="-1">Pinia 插件 <a class="header-anchor" href="#pinia-plugins" aria-label="Permalink to &quot;Pinia 插件 %{#pinia-plugins}%&quot;">​</a></h3><p>如果你有使用任何 pinia 插件，确保在调用 <code>createTestingPinia()</code> 时传入它们，这样它们就会被正确加载。<strong>不要使用 <code>testingPinia.use(MyPlugin)</code></strong> 来加载它们，而应该像正常的 pinia 那样：</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../src/stores/plugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 某些测试</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">      createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">        stubActions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#1E754F" })}"> false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">        plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><h2 id="e2e-tests" tabindex="-1">端到端测试 <a class="header-anchor" href="#e2e-tests" aria-label="Permalink to &quot;端到端测试 %{#e2e-tests}%&quot;">​</a></h2><p>对于 pinia，你不需要为端到端测试修改任何代码，这就是端到端测试的含义！也许你想测试 HTTP 请求，但这已经超出了本指南的范围😄。</p><h2 id="unit-test-components-vue-2" tabindex="-1">对组件单元测试(Vue 2) <a class="header-anchor" href="#unit-test-components-vue-2" aria-label="Permalink to &quot;对组件单元测试(Vue 2) %{#unit-test-components-vue-2}%&quot;">​</a></h2><p>当你使用的是 <a href="https://v1.test-utils.vuejs.org/en/" target="_blank" rel="noreferrer">Vue Test Utils 1</a> 时，请将 Pinia 安装在 <code>localVue</code> 上：</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> PiniaVuePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createLocalVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@vue/test-utils</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> localVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createLocalVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">localVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">use</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">PiniaVuePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">  localVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 使用 pinia 的测试实例！</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("cookbook/testing.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const testing = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  testing as default
};
