import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"witTableV2 高性能虚拟表格","description":"","frontmatter":{},"headers":[],"relativePath":"core-concepts/witTableV2.md","filePath":"core-concepts/witTableV2.md"}');
const _sfc_main = { name: "core-concepts/witTableV2.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="witTableV2" tabindex="-1">witTableV2 高性能虚拟表格 <a class="header-anchor" href="#witTableV2" aria-label="Permalink to &quot;witTableV2 高性能虚拟表格 %{#witTableV2}%&quot;">​</a></h1><p><code>witTableV2</code>是一个基于 Element Plus el-table-v2 封装的高性能虚拟表格组件，支持自动调整大小、自定义列设置、空数据处理等功能，适用于大数据量场景下的表格展示。组件提供了简洁的 API 和灵活的配置选项，能够满足各种复杂的表格需求。</p><h2 id="dome" tabindex="-1">用法实例 <a class="header-anchor" href="#dome" aria-label="Permalink to &quot;用法实例 %{#dome}%&quot;">​</a></h2><div class="language-vue vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">vue</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">template</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> class</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">table-container</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">witTableV2</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      table-name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">demo-table</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      :</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">table-data</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">tableData</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      :</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">columns</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">columns</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      :</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">show-overflow</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#1E754F" })}">false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      :</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">max-height</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">600</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  &lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">template</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> lang</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">ts</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> setup</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> ref</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">vue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 表格数据</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> tableData</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> ref</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">([</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    id</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">张三</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    age</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 25</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    address</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">北京市朝阳区</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    id</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 2</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">李四</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    age</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 30</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    address</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">上海市浦东新区</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">  // 更多数据...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">])</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// 列配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> columns</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> ref</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">([</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    key</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">id</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    title</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">ID</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    width</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 80</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    align</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">center</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    key</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    title</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">姓名</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    width</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 120</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    align</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">left</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    key</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">age</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    title</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">年龄</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    width</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 80</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    align</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">center</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    key</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">address</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    title</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">地址</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    width</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 200</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    align</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">left</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">])</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">style</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> scoped</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#999999", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">table-container</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">  height</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 100</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">%</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">  width</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 100</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">%</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">style</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span></code></pre></div><h2 id="API" tabindex="-1">API <a class="header-anchor" href="#API" aria-label="Permalink to &quot;API&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">  &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">props</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">tableData</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Array</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">[]</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">表格数据</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">columns</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Array</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">[]</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">列配置信息</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">autoHeight</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Boolean</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">是否自动撑开高度</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">height</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Number, String</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">&#39;100%&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">表格高度</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">maxHeight</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Number</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">0</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">表格最大高度</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">tableName</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">String</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">必传参数</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">本地存储的唯一键名，用于保存列配置</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">isShowTableSet</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Boolean</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">true</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">是否显示头部设置功能</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">isCustomLoading</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Boolean</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">是否自定义loading</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">isEmpty</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Boolean</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">true</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">是否显示自定义空数据模板</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">customEmpty</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Boolean</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">是否使用自定义空数据模板</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">showOverflow</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Boolean</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">true</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">文字超出是否换行显示，false为换行</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">...ElTableV2.props</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Object</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">-</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">继承 Element Plus ElTableV2 的所有属性</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">  &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">slots</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">empty</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">自定义空数据显示内容</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">  &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">events</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">...ElTableV2.events</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">继承 Element Plus ElTableV2 的所有事件</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">params</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">-</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">  &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">methods</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">tableMethods</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">调用表格内部方法的接口</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">params</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">name: 方法名, ...params: 方法参数</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">openTableSet</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">description</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">打开表格列设置对话框</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">      &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">params</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E2F2", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">-</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">}</span></span></code></pre></div><div class="tip custom-block"><p class="custom-block-title">TIP</p><ol><li>组件基于 Element Plus el-table-v2 开发，支持虚拟滚动，适合处理大数据量表格</li><li>通过 <code>tableName</code> 属性可以将列配置保存到本地存储，实现用户个性化设置</li><li>支持自动调整表格大小，适配不同的容器尺寸</li><li>当 <code>showOverflow</code> 设为 false 时，文字超出会自动换行显示</li><li>组件继承了 Element Plus el-table-v2 的所有属性和事件，可根据需求灵活配置</li></ol></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("core-concepts/witTableV2.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const witTableV2 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  witTableV2 as default
};
