import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"witMdEditor Markdown编辑器","description":"","frontmatter":{},"headers":[],"relativePath":"core-concepts/witMdEditor.md","filePath":"core-concepts/witMdEditor.md"}');
const _sfc_main = { name: "core-concepts/witMdEditor.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="witMdEditor" tabindex="-1">witMdEditor Markdown编辑器 <a class="header-anchor" href="#witMdEditor" aria-label="Permalink to &quot;witMdEditor Markdown编辑器 %{#witMdEditor}%&quot;">​</a></h1><p><code>witMdEditor</code>是一个基于 <code>md-editor-v3</code> 封装的 Markdown 编辑器组件，支持实时预览、语法高亮、双向数据绑定等功能，适用于需要在应用中集成 Markdown 编辑功能的场景。</p><h2 id="dome" tabindex="-1">用法实列 <a class="header-anchor" href="#dome" aria-label="Permalink to &quot;用法实列 %{#dome}%&quot;">​</a></h2><div class="language-vue vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">vue</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">template</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> style</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#998418" })}">height</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 500</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">px</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">witMdEditor</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> v-model</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">content</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> @</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">getPosition</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">handleGetPosition</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> class</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">mt-4</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">h3</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#393A34" })}">预览内容：</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">h3</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> v-html</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">htmlContent</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    &lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  &lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">div</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">template</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> lang</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">ts</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> setup</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> ref</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> computed</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">vue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> marked</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">marked</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> content</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> ref</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}"># Hello World</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#A65E2B" })}">\\n\\n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">这是一个 Markdown 编辑器示例</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> htmlContent</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> computed</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> marked</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">content</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">value</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">))</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> handleGetPosition</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> (</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">position</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> any</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">  console</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">log</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">当前光标位置：</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> position</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span></code></pre></div><h2 id="API" tabindex="-1">API <a class="header-anchor" href="#API" aria-label="Permalink to &quot;API&quot;">​</a></h2><table><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">属性名</th><th style="${ssrRenderStyle({ "text-align": "left" })}">类型</th><th style="${ssrRenderStyle({ "text-align": "left" })}">默认值</th><th style="${ssrRenderStyle({ "text-align": "left" })}">描述</th></tr></thead><tbody><tr><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>modelValue</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}">[<code>String</code>]</td><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>&#39;&#39;</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}">Markdown 内容，用于双向绑定</td></tr></tbody></table><h2 id="Events" tabindex="-1">Events <a class="header-anchor" href="#Events" aria-label="Permalink to &quot;Events&quot;">​</a></h2><table><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">事件名</th><th style="${ssrRenderStyle({ "text-align": "left" })}">描述</th><th style="${ssrRenderStyle({ "text-align": "left" })}">参数</th></tr></thead><tbody><tr><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>update:modelValue</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}">编辑器内容变化时触发</td><td style="${ssrRenderStyle({ "text-align": "left" })}">最新的 Markdown 内容</td></tr><tr><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>getPosition</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}">获取光标位置时触发</td><td style="${ssrRenderStyle({ "text-align": "left" })}">光标位置信息对象</td></tr></tbody></table><div class="tip custom-block"><p class="custom-block-title">TIP</p><ol><li><code>witMdEditor</code> 是基于 <code>md-editor-v3</code> 封装的组件，支持 <code>md-editor-v3</code> 的所有属性和事件，可以通过 <code>v-bind=&quot;$attrs&quot;</code> 传递额外属性</li><li>组件默认高度为 100%，可以通过外层容器控制编辑器高度</li><li>若需要自定义工具栏或编辑器行为，可以直接使用 <code>md-editor-v3</code> 组件</li><li>如需将 Markdown 转换为 HTML 显示，可使用 <code>marked</code> 等第三方库进行转换</li></ol></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("core-concepts/witMdEditor.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const witMdEditor = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  witMdEditor as default
};
