import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Testing stores","description":"","frontmatter":{},"headers":[],"relativePath":"en/cookbook/testing.md","filePath":"en/cookbook/testing.md"}');
const _sfc_main = { name: "en/cookbook/testing.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="Testing-stores" tabindex="-1">Testing stores <a class="header-anchor" href="#Testing-stores" aria-label="Permalink to &quot;Testing stores&quot;">​</a></h1><p>Stores will, by design, be used at many places and can make testing much harder than it should be. Fortunately, this doesn&#39;t have to be the case. We need to take care of three things when testing stores:</p><ul><li>The <code>pinia</code> instance: Stores cannot work without it</li><li><code>actions</code>: most of the time, they contain the most complex logic of our stores. Wouldn&#39;t it be nice if they were mocked by default?</li><li>Plugins: If you rely on plugins, you will have to install them for tests too</li></ul><p>Depending on what or how you are testing, we need to take care of these three things differently.</p><h2 id="Unit-testing-a-store" tabindex="-1">Unit testing a store <a class="header-anchor" href="#Unit-testing-a-store" aria-label="Permalink to &quot;Unit testing a store&quot;">​</a></h2><p>To unit test a store, the most important part is creating a <code>pinia</code> instance:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// stores/counter.spec.ts</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../src/stores/counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">describe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Counter Store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  beforeEach</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // creates a fresh pinia and makes it active</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // so it&#39;s automatically picked up by any useStore() call</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // without having to pass it to it: \`useStore(pinia)\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">())</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  it</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">increments</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">0</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  it</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">increments by amount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">10</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">10</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><p>If you have any store plugins, there is one important thing to know: <strong>plugins won&#39;t be used until <code>pinia</code> is installed in an App</strong>. This can be solved by creating an empty App or a fake one:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createApp</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">vue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../src/stores/plugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// same code as above...</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// you don&#39;t need to create one app per test</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> app</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createApp</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({})</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">beforeEach</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">().</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">use</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">  app</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">use</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  setActivePinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><h2 id="Unit-testing-components" tabindex="-1">Unit testing components <a class="header-anchor" href="#Unit-testing-components" aria-label="Permalink to &quot;Unit testing components&quot;">​</a></h2><p>This can be achieved with <code>createTestingPinia()</code>, which returns a pinia instance designed to help unit tests components.</p><p>Start by installing <code>@pinia/testing</code>:</p><div class="language-shell vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">shell</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}"> i</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B" })}"> -D</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}"> @pinia/testing</span></span></code></pre></div><p>And make sure to create a testing pinia in your tests when mounting a component:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@vue/test-utils</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// import any store you want to interact with in tests</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@/stores/myStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // uses the testing pinia!</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// state can be directly manipulated</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">my new name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// can also be done through patch</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">$patch</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}"> name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">new name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toBe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">new name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// actions are stubbed by default, meaning they don&#39;t execute their code by default.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// See below to customize this behavior.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toHaveBeenCalledTimes</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toHaveBeenLastCalledWith</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span></code></pre></div><p>Please note that if you are using Vue 2, <code>@vue/test-utils</code> requires a <a href="#Unit-test-components-Vue-2-">slightly different configuration</a>.</p><h3 id="Initial-State" tabindex="-1">Initial State <a class="header-anchor" href="#Initial-State" aria-label="Permalink to &quot;Initial State&quot;">​</a></h3><p>You can set the initial state of <strong>all of your stores</strong> when creating a testing pinia by passing an <code>initialState</code> object. This object will be used by the testing pinia to <em>patch</em> stores when they are created. Let&#39;s say you want to initialize the state of this store:</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> () </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({ </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 0</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">  // ...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><p>Since the store is named <em>&quot;counter&quot;</em>, you need to add a matching object to <code>initialState</code>:</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// somewhere in your test</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">      createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">        initialState</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">          counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> { </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 20</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }, </span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// start the counter at 20 instead of 0</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">        },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // uses the testing pinia!</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 20</span></span></code></pre></div><h3 id="Customizing-behavior-of-actions" tabindex="-1">Customizing behavior of actions <a class="header-anchor" href="#Customizing-behavior-of-actions" aria-label="Permalink to &quot;Customizing behavior of actions&quot;">​</a></h3><p><code>createTestingPinia</code> stubs out all store actions unless told otherwise. This allows you to test your components and stores separately.</p><p>If you want to revert this behavior and normally execute your actions during tests, specify <code>stubActions: false</code> when calling <code>createTestingPinia</code>:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}"> stubActions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#1E754F" })}"> false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> })],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// Now this call WILL execute the implementation defined by the store</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// ...but it&#39;s still wrapped with a spy, so you can inspect calls</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">expect</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">).</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">toHaveBeenCalledTimes</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span></code></pre></div><h3 id="Mocking-the-returned-value-of-an-action" tabindex="-1">Mocking the returned value of an action <a class="header-anchor" href="#Mocking-the-returned-value-of-an-action" aria-label="Permalink to &quot;Mocking the returned value of an action&quot;">​</a></h3><p>Actions are automatically spied but type-wise, they are still the regular actions. In order to get the correct type, we must implement a custom type-wrapper that is applies the <code>Mock</code> type to each action. <strong>This type depends on the testing framework you are using</strong>. Here is an example with Vitest:</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> Mock</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">vitest</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> type</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> Store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> StoreDefinition</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">function</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mockedStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">TStoreDef</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> extends</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> unknown</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">  useStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> TStoreDef</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> TStoreDef</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> extends</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> StoreDefinition</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  infer</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Id</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  infer</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> State</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  infer</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Getters</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  infer</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Actions</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  ?</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      Id</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      State</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      Getters</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">        [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">K</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> in</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> keyof</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Actions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">]</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Actions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">[</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">K</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">] </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">extends</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">          ...</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">args</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> infer</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Args</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">        ) </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> infer</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> ReturnT</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">          ?</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 👇 depends on your testing framework</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">            Mock</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">Args</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">, </span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">ReturnT</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">          :</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> Actions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">[</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">K</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    &gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">  :</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> ReturnType</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">TStoreDef</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">  return</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> as</span><span style="${ssrRenderStyle({ "--shiki-dark": "#97E1F1", "--shiki-light": "#2E8F82", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> any</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">}</span></span></code></pre></div><p>This can be used in tests to get a correctly typed store:</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> mockedStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">./mockedStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@/stores/myStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mockedStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// typed!</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">mockResolvedValue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">some value</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span></code></pre></div><h3 id="Specifying-the-createSpy-function" tabindex="-1">Specifying the createSpy function <a class="header-anchor" href="#Specifying-the-createSpy-function" aria-label="Permalink to &quot;Specifying the createSpy function&quot;">​</a></h3><p>When using Jest, or vitest with <code>globals: true</code>, <code>createTestingPinia</code> automatically stubs actions using the spy function based on the existing test framework (<code>jest.fn</code> or <code>vitest.fn</code>). If you are not using <code>globals: true</code> or using a different framework, you&#39;ll need to provide a <a href="/api/interfaces/pinia_testing.TestingOptions.html#createspy">createSpy</a> option:</p><div class="vp-code-group vp-adaptive-theme"><div class="tabs"><input type="radio" name="group-kBNks" id="tab--K2cdcI" checked="checked"><label for="tab--K2cdcI">vitest</label><input type="radio" name="group-kBNks" id="tab-pW1Gt_X"><label for="tab-pW1Gt_X">sinon</label></div><div class="blocks"><div class="language-ts vp-adaptive-theme active"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// NOTE: not needed with \`globals: true\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> vi</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">vitest</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  createSpy</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> vi</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">fn</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> sinon</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">sinon</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  createSpy</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> sinon</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">spy</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div></div></div><p>You can find more examples in <a href="https://github.com/vuejs/pinia/blob/v2/packages/testing/src/testing.spec.ts" target="_blank" rel="noreferrer">the tests of the testing package</a>.</p><h3 id="Mocking-getters" tabindex="-1">Mocking getters <a class="header-anchor" href="#Mocking-getters" aria-label="Permalink to &quot;Mocking getters&quot;">​</a></h3><p>By default, any getter will be computed like regular usage but you can manually force a value by setting the getter to anything you want:</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> () </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({ </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  getters</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> (</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">) </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> *</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 2</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 3</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 🪄 getters are writable only in tests</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// set to undefined to reset the default behavior</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// @ts-expect-error: usually it&#39;s a number</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#AB5959" })}"> undefined</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">double</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // 2 (=1 x 2)</span></span></code></pre></div><h3 id="Pinia-Plugins" tabindex="-1">Pinia Plugins <a class="header-anchor" href="#Pinia-Plugins" aria-label="Permalink to &quot;Pinia Plugins&quot;">​</a></h3><p>If you have any pinia plugins, make sure to pass them when calling <code>createTestingPinia()</code> so they are properly applied. <strong>Do not add them with <code>testingPinia.use(MyPlugin)</code></strong> like you would do with a regular pinia:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../src/stores/plugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// inside some test</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  global</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">      createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">        stubActions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#1E754F" })}"> false</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">        plugins</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">somePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><h2 id="E2E-tests" tabindex="-1">E2E tests <a class="header-anchor" href="#E2E-tests" aria-label="Permalink to &quot;E2E tests&quot;">​</a></h2><p>When it comes to Pinia, you don&#39;t need to change anything for E2E tests, that&#39;s the whole point of these tests! You could maybe test HTTP requests, but that&#39;s way beyond the scope of this guide 😄.</p><h2 id="Unit-test-components-Vue-2-" tabindex="-1">Unit test components (Vue 2) <a class="header-anchor" href="#Unit-test-components-Vue-2-" aria-label="Permalink to &quot;Unit test components (Vue 2)&quot;">​</a></h2><p>When using <a href="https://v1.test-utils.vuejs.org/" target="_blank" rel="noreferrer">Vue Test Utils 1</a>, install Pinia on a <code>localVue</code>:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> PiniaVuePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createLocalVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@vue/test-utils</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">@pinia/testing</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> localVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createLocalVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">localVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">use</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">PiniaVuePlugin</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> wrapper</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mount</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">Counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">  localVue</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> createTestingPinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // uses the testing pinia!</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/cookbook/testing.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const testing = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  testing as default
};
