import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderComponent, ssrRenderStyle } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Actions","description":"","frontmatter":{},"headers":[],"relativePath":"en/core-concepts/actions.md","filePath":"en/core-concepts/actions.md"}');
const _sfc_main = { name: "en/core-concepts/actions.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_VueSchoolLink = resolveComponent("VueSchoolLink");
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="Actions" tabindex="-1">Actions <a class="header-anchor" href="#Actions" aria-label="Permalink to &quot;Actions&quot;">​</a></h1>`);
  _push(ssrRenderComponent(_component_VueSchoolLink, {
    href: "https://vueschool.io/lessons/synchronous-and-asynchronous-actions-in-pinia",
    title: "Learn all about actions in Pinia"
  }, null, _parent));
  _push(`<p>Actions are the equivalent of <a href="https://vuejs.org/api/options-state.html#methods" target="_blank" rel="noreferrer">methods</a> in components. They can be defined with the <code>actions</code> property in <code>defineStore()</code> and <strong>they are perfect to define business logic</strong>:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">export</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    count</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 0</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  actions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // since we rely on \`this\`, we cannot use an arrow function</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">count</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">++</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    randomizeCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">count</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> Math</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">round</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}">100</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> *</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> Math</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">random</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">())</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><p>Like <a href="./getters.html">getters</a>, actions get access to the <em>whole store instance</em> through <code>this</code> with <strong>full typing (and autocompletion ✨) support</strong>. <strong>Unlike getters, <code>actions</code> can be asynchronous</strong>, you can <code>await</code> inside of actions any API call or even other actions! Here is an example using <a href="https://github.com/posva/mande" target="_blank" rel="noreferrer">Mande</a>. Note the library you use doesn&#39;t matter as long as you get a <code>Promise</code>. You could even use the native <code>fetch</code> function (browser only):</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> mande</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">mande</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> api</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> mande</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">/api/users</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">export</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useUsers</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">users</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    userData</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#AB5959" })}"> null</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // ...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  }),</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  actions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    async</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> registerUser</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">login</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> password</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">      try</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">        this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">userData</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> await</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> api</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">post</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> login</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> password</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">        showTooltip</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">\`</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Welcome back </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">userData</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">!</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">\`</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> catch</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> (</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">error</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">        showTooltip</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">error</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">        // let the form component display the error</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">        return</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> error</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><p>You are also completely free to set whatever arguments you want and return anything. When calling actions, everything will be automatically inferred!</p><p>Actions are invoked like regular functions and methods:</p><div class="language-vue vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">vue</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> setup</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// call the action as a method of the store</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">randomizeCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">template</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">  &lt;!-- Even on the template --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  &lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">button</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> @</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">click</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">=</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">randomizeCounter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#393A34" })}">Randomize</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">button</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">template</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span></code></pre></div><h2 id="Accessing-other-stores-actions" tabindex="-1">Accessing other stores actions <a class="header-anchor" href="#Accessing-other-stores-actions" aria-label="Permalink to &quot;Accessing other stores actions&quot;">​</a></h2><p>To consume another store, you can directly <em>use it</em> inside of the <em>action</em>:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useAuthStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">./auth-store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">export</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useSettingsStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">settings</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    preferences</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#AB5959" })}"> null</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // ...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  actions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    async</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> fetchUserPreferences</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">      const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> auth</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useAuthStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">      if</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> (</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">auth</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">isAuthenticated</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">        this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">preferences</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> await</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> fetchPreferences</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> else</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">        throw</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959", "--shiki-dark-font-weight": "bold", "--shiki-light-font-weight": "inherit" })}"> new</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> Error</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">User must be authenticated</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><h2 id="Usage-with-the-Options-API" tabindex="-1">Usage with the Options API <a class="header-anchor" href="#Usage-with-the-Options-API" aria-label="Permalink to &quot;Usage with the Options API&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_VueSchoolLink, {
    href: "https://vueschool.io/lessons/access-pinia-actions-in-the-options-api",
    title: "Access Pinia Getters via the Options API"
  }, null, _parent));
  _push(`<p>For the following examples, you can assume the following store was created:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// Example File Path:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// ./src/stores/counter.js</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">export</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  state</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> ({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">    count</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#2F798A" })}"> 0</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  actions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">count</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">++</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span></code></pre></div><h3 id="With-setup-" tabindex="-1">With <code>setup()</code> <a class="header-anchor" href="#With-setup-" aria-label="Permalink to &quot;With \`setup()\`&quot;">​</a></h3><p>While Composition API is not for everyone, the <code>setup()</code> hook can make Pinia easier to work with while using the Options API. No extra map helper functions needed!</p><div class="language-vue vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">vue</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../stores/counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">export</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> defineComponent</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">  setup</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">    return</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> counterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  methods</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    incrementAndPrint</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">      this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">      console</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">log</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">New Count:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#A65E2B", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> this</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">counterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">count</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">})</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span></code></pre></div><h3 id="Without-setup-" tabindex="-1">Without <code>setup()</code> <a class="header-anchor" href="#Without-setup-" aria-label="Permalink to &quot;Without \`setup()\`&quot;">​</a></h3><p>If you would prefer not to use Composition API at all, you can use the <code>mapActions()</code> helper to map actions properties as methods in your component:</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> mapActions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">pinia</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">import</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> from</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">../stores/counter</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">export</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}"> default</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}">  methods</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // gives access to this.increment() inside the component</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // same as calling from store.increment()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">    ...</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">mapActions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">]),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // same as above but registers it as this.myOwnName()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">    ...</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">mapActions</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">useCounterStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#998418" })}"> myOwnName</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">:</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}"> &#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">increment</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">}</span></span></code></pre></div><h2 id="Subscribing-to-actions" tabindex="-1">Subscribing to actions <a class="header-anchor" href="#Subscribing-to-actions" aria-label="Permalink to &quot;Subscribing to actions&quot;">​</a></h2><p>It is possible to observe actions and their outcome with <code>store.$onAction()</code>. The callback passed to it is executed before the action itself. <code>after</code> handles promises and allows you to execute a function after the action resolves. In a similar way, <code>onError</code> allows you to execute a function if the action throws or rejects. These are useful for tracking errors at runtime, similar to <a href="https://vuejs.org/guide/best-practices/production-deployment#tracking-runtime-errors" target="_blank" rel="noreferrer">this tip in the Vue docs</a>.</p><p>Here is an example that logs before running actions and after they resolve/reject.</p><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> unsubscribe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> someStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">$onAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  ({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // name of the action</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    store</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // store instance, same as \`someStore\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    args</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // array of parameters passed to the action</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    after</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // hook after the action returns or resolves</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    onError</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}"> // hook if the action throws or rejects</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  })</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // a shared variable for this specific action call</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">    const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> startTime</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> Date</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">now</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // this will trigger before an action on \`store\` is executed</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">    console</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">log</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">\`</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Start &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">&quot; with params [</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">args</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">join</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">, </span><span style="${ssrRenderStyle({ "--shiki-dark": "#DEE492", "--shiki-light": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">].</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">\`</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // this will trigger if the action succeeds and after it has fully run.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // it waits for any returned promised</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    after</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">((</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">result</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">      console</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">log</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">        \`</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Finished &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">&quot; after </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">          Date</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">now</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> -</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}"> startTime</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">        }</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">ms.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#A65E2B" })}">\\n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Result: </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">result</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">    // this will trigger if the action throws or returns a promise that rejects</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">    onError</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">((</span><span style="${ssrRenderStyle({ "--shiki-dark": "#FFB86C", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}">error</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =&gt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">      console</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">warn</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">        \`</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Failed &quot;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">name</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">&quot; after </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">Date</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">now</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}"> -</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}"> startTime</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">ms.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#A65E2B" })}">\\n</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">Error: </span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">\${</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B56959" })}">error</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}">}</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B56959" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#E7EE98", "--shiki-light": "#B5695999" })}">\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">      )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">    })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// manually remove the listener</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">unsubscribe</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span></code></pre></div><p>By default, <em>action subscriptions</em> are bound to the component where they are added (if the store is inside a component&#39;s <code>setup()</code>). Meaning, they will be automatically removed when the component is unmounted. If you also want to keep them after the component is unmounted, pass <code>true</code> as the second argument to <em>detach</em> the <em>action subscription</em> from the current component:</p><div class="language-vue vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">vue</span><pre class="shiki shiki-themes dracula-soft vitesse-light vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#B07D48", "--shiki-dark-font-style": "italic", "--shiki-light-font-style": "inherit" })}"> setup</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#AB5959" })}">const</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}"> someStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#999999" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}"> useSomeStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#7B7F8B", "--shiki-light": "#A0ADA0" })}">// this subscription will be kept even after the component is unmounted</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">someStore</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">.</span><span style="${ssrRenderStyle({ "--shiki-dark": "#62E884", "--shiki-light": "#59873A" })}">$onAction</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">(</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#B07D48" })}">callback</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">,</span><span style="${ssrRenderStyle({ "--shiki-dark": "#BF9EEE", "--shiki-light": "#1E754F" })}"> true</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&lt;/</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F286C4", "--shiki-light": "#1E754F" })}">script</span><span style="${ssrRenderStyle({ "--shiki-dark": "#F6F6F4", "--shiki-light": "#999999" })}">&gt;</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/core-concepts/actions.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const actions = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  actions as default
};
